import * as dotenv from 'dotenv';
dotenv.config();

export const JwtConstants = {
  privateKeyPathEnv: process.env.JWT_PRIVATE_KEY_PATH,
  publicKeyPathEnv: process.env.JWT_PUBLIC_KEY_PATH,
  secret: process.env.JWT_SECRET,
};

export const dummyToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndvbmF0bzYwNjBAY2hhbWJpbGUuY29tIiwic3ViIjoiMSIsInpvbmVJZCI6IjEiLCJmaXJzdE5hbWUiOiJNYXhpbWUiLCJsYXN0TmFtZSI6IkdvbmFsb25zIiwiem9uZSI6IlNlYm9yZSBGYXJtcyBFUFoiLCJwZXJtaXNzaW9ucyI6WyJsaWNlbnNpbmciLCJ2aWV3X3VzZXJzIiwiY3JlYXRlX3VzZXIiLCJlZGl0X3VzZXIiLCJkZWxldGVfdXNlciIsInJlc2V0X3Bhc3N3b3JkIiwidmlld19yb2xlc19hbmRfcGVybWlzc2lvbnMiLCJjcmVhdGVfcm9sZXNfYW5kX3Blcm1pc2lvbnMiLCJlZGl0X3JvbGVzX2FuZF9wZXJtaXNpb25zIiwidmlld19hdWRpdF9sb2ciLCJyZXNldF91c2VyX3Bhc3N3b3JkIiwidmlld190cmFuc2FjdGlvbl9oaXN0b3J5Iiwidmlld19kYXNoYm9hcmQiLCJyZWdpc3Rlcl9vcmdhbmlzYXRpb24iLCJ2aWV3X29yZ2FuaXNhdGlvbiIsImVkaXRfb3JnYW5pc2F0aW9uIl0sImV4cGlyZXNJbiI6IjFoIiwiaWF0IjoxNjk0Mjk5OTIxLCJleHAiOjE2OTQzMDM1MjF9.uwhclV39FuHJsEYnC1v7YwREclhLC7j-hxhllFRmz-A';
